const data = [
  {
    stage: ["@group:device-management"],
    _id: "5f8813256927a9001725060f",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792258256",
    jobId: "792258256",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "183029edca7e5e1e2c22bb40f8c8af02a9f355b7",
    duration: 103373,
    records: {
      "backup/fail-t2": "success",
      "backup/misc-t2": "success",
      "backup/success-t2": "success",
      "firmware/firmware": "success",
      "recovery/dry-run-persistence-t2": "success",
      "recovery/dry-run-t1": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:metadata"],
    _id: "5f8813286927a90017250610",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792258252",
    jobId: "792258252",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "183029edca7e5e1e2c22bb40f8c8af02a9f355b7",
    duration: 95822,
    records: {
      "metadata/account-metadata": "success",
      "metadata/address-metadata": "success",
      "metadata/api-errors": "success",
      "metadata/interval-fetching": "success",
      "metadata/output-labeling": "success",
      "metadata/remembered-device": "success",
      "metadata/wallet-metadata": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:suite"],
    _id: "5f8813716927a90017250611",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792258249",
    jobId: "792258249",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "183029edca7e5e1e2c22bb40f8c8af02a9f355b7",
    duration: 106037,
    records: {
      "browser/edge": "success",
      "browser/iphone-chrome": "success",
      "browser/outdated-chrome": "success",
      "browser/outdated-firefox": "success",
      "settings/device": "success",
      "settings/general": "success",
      "settings/log": "success",
      "suite/analytics": "success",
      "suite/connecting-devices": "success",
      "suite/initial-run": "success",
      "suite/passphrase": "success",
      "suite/remembering-devices": "success",
      "suite/static-pages": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:onboarding"],
    _id: "5f8813b56927a90017250612",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792258258",
    jobId: "792258258",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "183029edca7e5e1e2c22bb40f8c8af02a9f355b7",
    duration: 197117,
    records: {
      "onboarding/create-wallet-t1": "success",
      "onboarding/create-wallet-t2": "success",
      "onboarding/hologram": "success",
      "onboarding/recovery-advanced-t1": "success",
      "onboarding/recovery-basic-t1": "success",
      "onboarding/recovery-fail-t2": "success",
      "onboarding/recovery-persistence-t2": "success",
      "onboarding/recovery-success-t2": "success",
      "onboarding/steps-order": "success",
      "onboarding/transport": "success",
      "onboarding/unexpected-states": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:metadata"],
    _id: "5f8817d06927a90017250613",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792308138",
    jobId: "792308138",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "90aa5db1214b5144bacbe4cbbbb81f61078c86f3",
    duration: 96448,
    records: {
      "metadata/account-metadata": "success",
      "metadata/address-metadata": "success",
      "metadata/api-errors": "success",
      "metadata/interval-fetching": "success",
      "metadata/output-labeling": "success",
      "metadata/remembered-device": "success",
      "metadata/wallet-metadata": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:suite"],
    _id: "5f8818186927a90017250614",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792308136",
    jobId: "792308136",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "90aa5db1214b5144bacbe4cbbbb81f61078c86f3",
    duration: 105165,
    records: {
      "browser/edge": "success",
      "browser/iphone-chrome": "success",
      "browser/outdated-chrome": "success",
      "browser/outdated-firefox": "success",
      "settings/device": "success",
      "settings/general": "success",
      "settings/log": "success",
      "suite/analytics": "success",
      "suite/connecting-devices": "success",
      "suite/initial-run": "success",
      "suite/passphrase": "success",
      "suite/remembering-devices": "success",
      "suite/static-pages": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:device-management"],
    _id: "5f8818216927a90017250615",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792308139",
    jobId: "792308139",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "90aa5db1214b5144bacbe4cbbbb81f61078c86f3",
    duration: 176228,
    records: {
      "backup/fail-t2": "success",
      "backup/misc-t2": "retried",
      "backup/success-t2": "success",
      "firmware/firmware": "success",
      "recovery/dry-run-persistence-t2": "success",
      "recovery/dry-run-t1": "success",
    },
    __v: 0,
  },
  {
    stage: ["@group:onboarding"],
    _id: "5f88185a6927a90017250616",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792308140",
    jobId: "792308140",
    branch: "tests-revisit-failing",
    commitMessage: "test(e2e): reorganize\n",
    commitSha: "90aa5db1214b5144bacbe4cbbbb81f61078c86f3",
    duration: 193528,
    records: {
      "onboarding/create-wallet-t1": "success",
      "onboarding/create-wallet-t2": "success",
      "onboarding/hologram": "success",
      "onboarding/recovery-advanced-t1": "success",
      "onboarding/recovery-basic-t1": "success",
      "onboarding/recovery-fail-t2": "success",
      "onboarding/recovery-persistence-t2": "success",
      "onboarding/recovery-success-t2": "success",
      "onboarding/steps-order": "success",
      "onboarding/transport": "success",
      "onboarding/unexpected-states": "success",
    },
    __v: 0,
  },
  {
    stage: ["@stable/metadata"],
    _id: "5f8824876927a90017250617",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792404346",
    jobId: "792404346",
    branch: "develop",
    commitMessage: "ci: hotfix nix jobs\n",
    records: {
      "metadata/account-metadata": "success",
      "metadata/address-metadata": "success",
      "metadata/api-errors": "success",
      "metadata/interval-fetching": "success",
      "metadata/output-labeling": "success",
      "metadata/remembered-device": "success",
      "metadata/wallet-metadata": "success",
    },
    __v: 0,
  },
  {
    stage: ["@stable/device-management"],
    _id: "5f8824bc6927a90017250618",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792404348",
    jobId: "792404348",
    branch: "develop",
    commitMessage: "ci: hotfix nix jobs\n",
    records: {
      "backup/fail-t2": "success",
      "backup/misc-t2": "success",
      "backup/success-t2": "success",
      "firmware/firmware": "success",
      "onboarding/create-wallet-t1": "success",
      "onboarding/create-wallet-t2": "success",
      "onboarding/hologram": "success",
      "onboarding/steps-order": "success",
      "onboarding/transport": "success",
      "onboarding/unexpected-states": "success",
    },
    __v: 0,
  },
  {
    stage: ["@stable/suite"],
    _id: "5f8824e36927a90017250619",
    jobUrl:
      "https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/792404341",
    jobId: "792404341",
    branch: "develop",
    commitMessage: "ci: hotfix nix jobs\n",
    records: {
      "browser/edge": "success",
      "browser/iphone-chrome": "success",
      "browser/outdated-chrome": "success",
      "browser/outdated-firefox": "success",
      "settings/device": "success",
      "settings/general": "success",
      "settings/log": "success",
      "suite/analytics": "success",
      "suite/connecting-devices": "success",
      "suite/initial-run": "success",
      "suite/passphrase": "success",
      "suite/remembering-devices": "success",
      "suite/static-pages": "success",
    },
    __v: 0,
  },
];

export default data;
